# basically my rewrite of mbuffet's sval layout

keyboard:
  matrix_positions:
    # finger keys (north west center east south)
    - [
      # left pinky
               [ 2, 1],
      [ 1, 2], [ 2, 2], [ 3, 2],
               [ 2, 3],
      # left ring
               [ 5, 1],
      [ 4, 2], [ 5, 2], [ 6, 2],
               [ 5, 3],
      # left middle
               [ 8, 1],
      [ 7, 2], [ 8, 2], [ 9, 2],
               [ 8, 3],
      # left index
               [11, 1],
      [10, 2], [11, 2], [12, 2],
               [11, 3],

      # right index
               [14, 1],
      [13, 2], [14, 2], [15, 2],
               [14, 3],
      # right middle
               [17, 1],
      [16, 2], [17, 2], [18, 2],
               [17, 3],
      # right ring
               [20, 1],
      [19, 2], [20, 2], [21, 2],
               [20, 3],
      # right pinky
               [23, 1],
      [22, 2], [23, 2], [24, 2],
               [23, 3],
    ]

    # thumb keys (for left: pad double-down nail up down knuckle)
    # basically, near-physical layout
    - [
      # left thumb
      [10, 4], [11, 4], [12, 4],
      [10, 5], [11, 5], [12, 5],
      # right thumb
      [13, 4], [14, 4], [15, 4],
      [13, 5], [14, 5], [15, 5],
    ]

  # should actually just be the same as above
  positions:
    # finger keys (north west center east south)
    - [
      # left pinky
               [ 2, 1],
      [ 1, 2], [ 2, 2], [ 3, 2],
               [ 2, 3],
      # left ring
               [ 5, 1],
      [ 4, 2], [ 5, 2], [ 6, 2],
               [ 5, 3],
      # left middle
               [ 8, 1],
      [ 7, 2], [ 8, 2], [ 9, 2],
               [ 8, 3],
      # left index
               [11, 1],
      [10, 2], [11, 2], [12, 2],
               [11, 3],

      # right index
               [14, 1],
      [13, 2], [14, 2], [15, 2],
               [14, 3],
      # right middle
               [17, 1],
      [16, 2], [17, 2], [18, 2],
               [17, 3],
      # right ring
               [20, 1],
      [19, 2], [20, 2], [21, 2],
               [20, 3],
      # right pinky
               [23, 1],
      [22, 2], [23, 2], [24, 2],
               [23, 3],
    ]

    # thumb keys (for left: pad double-down nail up down knuckle)
    # basically, near-physical layout
    - [
      # left thumb
      [10, 4], [11, 4], [12, 4],
      [10, 5], [11, 5], [12, 5],
      # right thumb
      [13, 4], [14, 4], [15, 4],
      [13, 5], [14, 5], [15, 5],
    ]

  directions:
    # fingers
    - [
      # left hand
      North, Out, Center, In, South,
      North, Out, Center, In, South,
      North, Out, Center, In, South,
      North, Out, Center, In, South,

      # right hand
      North, In, Center, Out, South,
      North, In, Center, Out, South,
      North, In, Center, Out, South,
      North, In, Center, Out, South,
    ]

    # thumbs (left, right)
    - [
      Pad, DoubleDown, Nail, Up, Down, Knuckle,
      Nail, DoubleDown, Pad, Knuckle, Down, Up,
    ]

  hands:
    # fingers
    - [
       Left,  Left,  Left,  Left,  Left,
       Left,  Left,  Left,  Left,  Left,
       Left,  Left,  Left,  Left,  Left,
       Left,  Left,  Left,  Left,  Left,
      Right, Right, Right, Right, Right,
      Right, Right, Right, Right, Right,
      Right, Right, Right, Right, Right,
      Right, Right, Right, Right, Right,
    ]

    # thumbs
    - [
       Left,  Left,  Left,  Left,  Left,  Left,
      Right, Right, Right, Right, Right, Right,
    ]

  fingers:
    - [
       Pinky,  Pinky,  Pinky,  Pinky,  Pinky,
        Ring,   Ring,   Ring,   Ring,   Ring,
      Middle, Middle, Middle, Middle, Middle,
       Index,  Index,  Index,  Index,  Index,

       Index,  Index,  Index,  Index,  Index,
      Middle, Middle, Middle, Middle, Middle,
        Ring,   Ring,   Ring,   Ring,   Ring,
       Pinky,  Pinky,  Pinky,  Pinky,  Pinky,
    ]

    - [
      Thumb, Thumb, Thumb, Thumb, Thumb, Thumb,
      Thumb, Thumb, Thumb, Thumb, Thumb, Thumb,
    ]

  key_costs:
    - [
      # left pinky
         99,
      6, 3, 4,
         3,
      # left ring
         7,
      8, 2, 5,
         2,
      # left middle
         6,
      4, 2, 3,
         2,
      # left index
         6,
      3, 2, 5,
         2,

      # right index
         6,
      5, 2, 3,
         2,
      # right middle
         6,
      3, 2, 4,
         2,
      # right ring
         7,
      5, 2, 8,
         2,
      # right pinky
         99,
      4, 3, 6,
         3,
    ]

    - [
      # left thumb
      2, 9, 5,
      6, 3, 4,
      # right thumb
      5, 9, 2,
      4, 3, 6,
    ]

  unbalancing_positions:
    # fingers
    - [
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],

      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
    ]

    # thumbs
    - [
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
    ]

  symmetries:
    # fingers
    - [
       1,  2,  3,  4,  5,
       6,  7,  8,  9, 10,
      11, 12, 13, 14, 15,
      16, 17, 18, 19, 20,

      20, 19, 18, 17, 16,
      15, 14, 13, 12, 11,
      10,  9,  8,  7,  6,
       5,  4,  3,  2,  1,
    ]

    # thumbs
    - [
      21, 22, 23, 24, 25, 26,
      26, 25, 24, 23, 22, 21,
    ]

  finger_resting_positions:
    Left:
      Pinky:  [ 2, 2]
      Ring:   [ 5, 2]
      Middle: [ 8, 2]
      Index:  [11, 2]
      Thumb:  [11, 5]

    Right:
      Thumb:  [14, 5]
      Index:  [14, 2]
      Middle: [17, 2]
      Ring:   [20, 2]
      Pinky:  [23, 2]

  # this... just looks horrid in here, sorry
  plot_template: |2
      {{0}}       {{5}}       {{10}}       {{15}}          {{20}}       {{25}}       {{30}}       {{35}}
    {{1}} {{2}} {{3}}   {{6}} {{7}} {{8}}   {{11}} {{12}} {{13}}   {{16}} {{17}} {{18}}      {{21}} {{22}} {{23}}   {{26}} {{27}} {{28}}   {{31}} {{32}} {{33}}   {{36}} {{37}} {{38}}
      {{4}}       {{9}}       {{14}}       {{19}}          {{24}}       {{29}}       {{34}}       {{39}}

                            {{40}} {{41}} {{42}}      {{46}} {{47}} {{48}}
                            {{43}} {{44}} {{45}}      {{49}} {{50}} {{51}}

  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}}{{6}}{{7}}{{8}}{{9}}{{10}}{{11}}{{12}}{{13}}{{14}}{{15}}{{16}}{{17}}{{18}}{{19}}{{20}}{{21}}{{22}}{{23}}{{24}}{{25}}{{26}}{{27}}{{28}}{{29}}{{30}}{{31}}{{32}}{{33}}{{34}}{{35}}{{36}}{{37}}{{38}}{{39}}{{40}}{{41}}{{42}}{{43}}{{44}}{{45}}{{46}}{{47}}{{48}}{{49}}{{50}}{{51}}

# re. this: start with HD-PM for sval
base_layout:
  # set-subtracted during the duplicate/unsupported check
  placeholder: "□"
  keys:
    # fingers
    - [
      # left pinky
             ["□"],
      ["q"], ["c"], ["z"],
             ["b"],
      # left ring
             ["□"],
      ["□"], ["i"], ["□"],
             ["y"],
      # left middle
             ["□"],
      ["□"], ["e"], ["□"],
             ["o"],
      # left index
             ["□"],
      ["□"], ["a"], ["□"],
             ["u"],

      # right index
             ["m"],
      ["k"], ["h"], ["x"],
             ["l"],
      # right middle
             ["g"],
      ["j"], ["t"], ["□"],
             ["d"],
      # right ring
             ["w"],
      ["□"], ["n"], ["□"],
             ["p"],
      # right pinky
             ["v"],
      ["□"], ["s"], ["□"],
             ["f"],
    ]

    # thumbs
    - [
      # left thumb
      [" "], ["□"], ["□"],
      ["□"], ["⇧"], ["□"],
      # right thumb
      ["□"], ["□"], ["r"],
      ["□"], ["□"], ["□"],
    ]

  fixed_keys:
    # fingers
    - [
      # left pinky
             false,
      false, false, false,
             false,

      # left ring
             false,
      false, false, false,
             false,

      # left middle
             false,
      false, false, false,
             false,

      # left index
             false,
      false, false, false,
             false,

      # right index
             false,
      false, false, false,
             false,

      # right middle
             false,
      false, false, false,
             false,

      # right ring
             false,
      false, false, false,
             false,

      # right pinky
             false,
      false, false, false,
             false,
    ]

    # thumbs
    - [
      # left thumb
        true,  true,  true,
        true,  true,  true,
      # right thumb
        true,  true, false,
        true,  true,  true,
    ]

  # everything else is pretty standard, modifiers TODO

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: []

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 1

  # modifier types can be "hold", "one_shot", and "long_press"
  #
  # "hold" and "one_shot" modifiers require a field "value" holding a list of
  # either matrix positions or symbols acting as modifiers
  modifiers:
    # shift / first alternate layer
    - Left:
        type: hold
        value: [[11, 5]]
      Right:
        type: hold
        value: []
